# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_type', models.PositiveSmallIntegerField(choices=[(1, b'Full notification'), (2, b'Web only notification'), (3, b'Email only notification')], default=1)),
                ('creation_dt', models.DateTimeField(auto_now_add=True)),
                ('displayed', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('delivery_response', models.TextField(blank=True, help_text=b'SMTP error codes and messages')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
